services:
  cache:
    image: pgvector/pgvector:pg17
    container_name: qbank-cache
    environment:
      - POSTGRES_USER=qbank
      - POSTGRES_PASSWORD=qbank
      - POSTGRES_DB=qbank
    ports:
      - 5432:5432
    volumes:
      - ./assets/postgres:/var/lib/postgresql/data
    networks:
      - qbank

networks:
  qbank:
